services:
  llamastack:
    image: llamastack/distribution-together
    ports:
      - "8321:8321"
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    entrypoint: bash -c "python -m llama_stack.distribution.server.server --template together"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
