name: runpod
distribution_spec:
  description: Use Runpod for running LLM inference
  providers:
    inference: remote::runpod
    memory: meta-reference
    safety: meta-reference
    agents: meta-reference
    telemetry: meta-reference
